### PR TITLE
upgrade to kibana 5

### PR DESCRIPTION
**Pull request by ytzlax**

### CODE REVIEW

**Comment by ytzlax** [comment]
I still not write the code that the detect which kibana version using

**Comment by bondib** [comment]
Hi @ytzlax .
It's a problem if you don't detect yet the kibana version - as it will break current use of the plugin with kibana 4 and therefore I can't merge the request yet.

Let me know if you can find a way to support both 4 & 5 and if not - we will open a new branch for 5.
Any other ideas?

**Comment by schwicke** [comment]
thanks for the patch! It would be nice to have it merged!

**Comment by ytzlax** [comment]
look at #9

**Comment by bondib** [comment]
HI @ytzlax and sorry for the VERY late reply.
I've tried using your pull request with kibana 5.2.3 and it doesn't work well.
Actully-  the original code - just works...

So what I'm doing is opening a new branch for 5 and putting almost the original hack.js code there - just updating the env (they are now using the plugin builder), index.js (which changed a bit) and installation details for kibana 5.

Will be done in a couple of hours.
Sorry everyone for the long delay - we only now (yes - took a while) moving to elastic 5 / kibana 5 and therefore I couldn't verify it works well till now.

**Comment by bondib** [comment]
Done

**Pull request closed without merging**
